### ISSUE TITLE
Why changing something without user interaction?

### ISSUE THREAD

**Issue by ansgarschulte** [bolliy/ioBroker.sun2000#16]
https://github.com/bolliy/ioBroker.sun2000/blob/5bf048e03a261e901d6807dc3f2995880b376367/main.js#L156C51-L156C51

Some question here:

1.  I have a LUNA2000 and my storageModel is 0?!
2. Why do you change the config to this?

**Comment by bolliy** [comment]
It is the preparation for being able to obtain cheap stock market electricity via tibber on a time-controlled basis. But I will comment it out in the next version. You can easily switch the working mode from "TOU" to "maximum self-consuption" via the app.
Then I don't understand the statement/question about storageModel 0? The storage/battery LUNA2000 has the value of storageModel 2.

**Comment by ansgarschulte** [comment]
I debugged the adapter locally with my storage... and I get a storageModel == 0 instead of 2. And I have a LUNA2000 connected.
<img width="389" alt="image" src="https://github.com/bolliy/ioBroker.sun2000/assets/1299623/25e3ecc0-83aa-4a2c-9de2-13fb03acb31c">

**Comment by bolliy** [comment]
The modbus definition description (https://www.photovoltaikforum.com/core/attachment/315028-solar-inverter-modbus-interface-definitions-pdf/ Page 64) is written the value 2 in register 47089 for LUNA2000. Maybe something is configured incorrectly?

**Comment by bolliy** [comment]
Can I close the issue? This function is disabled in the current version.

**Comment by ansgarschulte** [comment]
yes

Am Fr., 12. Jan. 2024 um 13:50 Uhr schrieb bolliy ***@***.***
