### ISSUE TITLE
Expand Adapter that we can use 3 Inverters

### ISSUE THREAD

**Issue by torkel25** [bolliy/ioBroker.sun2000#18]
Hello

i have installed the Adapter and i'm using it now with 2 Inverters and one Battery. Some values are not there but i don't know if it's on my setup as i use 3 inverters (kaskadiert)

could you expand this adapter that we could use 3 inverters? One Master and 2 Slaves?

thanks a lot!

**Comment by bolliy** [comment]
This will be implemented in the next version. Thank you for your request.

**Comment by bolliy** [comment]
Is implemented. Now 5 inverters can be used ;)
