### ISSUE TITLE
Probleme mit der Zeit?!

### ISSUE THREAD

**Issue by luckyheiko** [bolliy/ioBroker.sun2000#34]
Hallo 

danke schon mal für den Adapter, benutze diesen nun seit 1 Woche und bekomme immer

sun2000.0 | 2024-01-21 15:41:27.555 | warn | Not all data can be read! Please reduce the intervall value.
-- | -- | -- | --
sun2000.0 | 2024-01-21 15:16:27.540 | warn | Not all data can be read! Please reduce the intervall value.

sun2000.0 | 8442 | 2024-01-21 18:11:45.024 | warn | Error while reading from 192.168.10.18: [37700\|100] id: 1 '' with : Timed out
-- | -- | -- | -- | --
sun2000.0 | 8442 | 2024-01-21 18:11:39.524 | warn | Error while reading from 192.168.10.18: [37100\|114] id: 1 '' with : TcpRTUBufferedPort Connection Timed Out

</body>
</html>

könnte dies an meiner Dongle Version liegen?

  | V100R001C00SPC159
-- | --

habe die Version 0.1.3 und die Zeit schon auf 30 sek gestellt, aber gibt/gab keine Änderung.

</body>
</html>

**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by bolliy** [comment]
Das ist ein bug. Die Fehlermeldung ist einfach falsch. Bitte vorerst ignorieren!
Im nächsten Update behebe ich den Fehler. 
Danke für den Hinweis.

VG Stephan

**Comment by bolliy** [comment]
Wie viele WR betreibst du?

**Comment by luckyheiko** [comment]
Habe nur 1 WR 
SUN2000-8KTL-M1 / 15kWh Speicher und sonst nur Dongle und das Smartmeter. 
eigentlich noch die WB, aber die WB ist zu 90% vom Netz getrennt.

**Comment by bolliy** [comment]
Danke, nur für meine Statistik ;)

**Comment by luckyheiko** [comment]
Hallo 

hab gerade noch nen fehler bemerkt. 
der WR hat die oben genannte FW.

auf dem Dongle (SDongleA-05) habe ich die V200R022C10SPC108
also WR V100R001C00SPC159

**Comment by bolliy** [comment]
Please install the new version and test again.
Stephan

**Comment by luckyheiko** [comment]
wow
das ging schnell O.o
hab instaliert und bis jetzt gibts keinen fehler.
wenn ich mich noch mal melde, kannst hier zu machen.

DANKE

**Comment by luckyheiko** [comment]
muss mich leider noch mal melden.'
<html><body>

sun2000.0 | 2024-01-24 19:56:35.502 | warn | Error while reading from 192.168.10.18: [37765\|2] id: 1 '' with : Timed out
-- | -- | -- | --
sun2000.0 | 2024-01-24 19:56:05.502 | warn | Error while reading from 192.168.10.18: [37765\|2] id: 1 '' with : Timed out
sun2000.0 | 2024-01-24 19:55:31.221 | warn | Error while reading from 192.168.10.18: [37765\|2] id: 1 '' with : Data length error, expected 9 got 7
sun2000.0 | 2024-01-24 19:48:05.502 | warn | Error while reading from 192.168.10.18: [37765\|2] id: 1 '' with : Timed out


</body>
</html>

denke aber das diese fehler kommen, da der 'dongle' aufgeweckt wird (da WR im standby) und dann zu lange braucht?!
kann man hier die Abfrage eingrenzen, wenn der WR im Standby oder so? (halt im winter / nacht)

**Comment by bolliy** [comment]
Hallo, mein WR geht bisher nicht in den Standby. Wenn der Dongle nicht antwortet, erhält man natürlich auche keine Daten. Hast du eine Idee wie ich eine Unterscheidung zwischen Stanby und Fehlverhalten vornehmen könnte?
Außerdem frage ich mich, wieso der WR/Dongle in den Standby geht, wenn doch immer Daten abgefragt werden?
Da ich auch von anderer Seite schon über den Stanby-Modus gehört habe, frage ich mich wo diese Funktion aktiviert wird?

**Comment by bolliy** [comment]
https://www.photovoltaikforum.com/thread/186188-sun2000-8ktl-m1-und-sonnenlichterkennung-standby-mit-luna2000-5kw/

Liegt es daran, dass der SOC auf 0% gegangen ist? Dann geht der WR wohl in den Stanby Mode.
Das können wir Softwareseitig leicht ändern. Meiner läuft zwischen 10%-90%

**Comment by bolliy** [comment]
Ja, nun geht mein WR auch in den Standby. Ich habe das AC-seitige Laden ausgeschaltet und schwupps geht der WR in Standby.
Ich überlege mir mal etwas ....
Stephan

**Comment by luckyheiko** [comment]
sun2000.0.inverter.0.battery.SOC = Discharge Cutoff Capacity und Input power =0 
dann lass den WR / Dongle schlafen gehen.
dieses 'Problem' tritt auch nur (in meinen augen) im Winter auf, wenn eben die Batterie keinen SOC mehr hat und der WR wegen Energiespargründen die Augen zumachen möchte.

**Comment by bolliy** [comment]
Idee: Ich werde den Status Register 32089 auswerten und in diesem als Klartext in einem State hinterlegen. Sollte der WR im Standby Mode sein, werden gescheiterte Verbindungsaufbauversuche zum Dongle nicht mehr als Warnung sodern als Debug oder Info deklariert. Ich ändere mal den Label deines Issue auf enhancement. 
Stephan

**Comment by bolliy** [comment]
Hallo, kannst du mir bitte noch sagen auf welchen Wert der State **sun2000.0.inverter.0.deviceStatus** der WR bei dir geht?
Bei mir steht der  sun2000.0.inverter.0.deviceStatus normalerweise auf 512. Wenn allerdings die Bedingung:
sun2000.0.inverter.0.battery.SOC = Discharge Cutoff Capacity und Input power =0
besteht dann geht mein WR auf 40960. Allerdings antwortet mein Dongle ohne Fehler.

Stephan

**Comment by luckyheiko** [comment]
![grafik](https://github.com/bolliy/ioBroker.sun2000/assets/26415601/9cd95146-6d93-4745-823a-3723631a8139)
WR hat 'end' SOC (15% erreicht) und ist im 'schlaf'

**Comment by bolliy** [comment]
Bitte mal die V0.3.0 installieren und testen...
https://forum.iobroker.net/topic/71768/test-adapter-sun2000-v0-1-x-huawei-wechselrichter
Stephan

**Comment by bolliy** [comment]
Wenn ich das richtg sehe hast du den smart charger von Huawei im Einsatz. Dieser greift konkurierend ebenfalls auf den modbus zu. Das führt unweigerlich zu timeout Fehler beim Adapter und beim charger. Ein gleichzeitiger Zugriff auf modbus (seriell) ist nicht möglich. 
Hier hilft nur ein sog. modbus-proxy oder der Einsatz eines smartLoggers von Huawei!

Siehe:
https://www.photovoltaikforum.com/thread/208282-modbus-register-f%C3%BCr-huawei-fusioncharger-wallbox/

Stephan

**Comment by bolliy** [comment]
Hallo Heiko, bitte dein Anliegen nun testen!
Siehe: https://forum.iobroker.net/post/1128119

Stephan

**Comment by luckyheiko** [comment]
Hallo 
habe gestern noch die 31er instaliert. Bis jetzt keine Fehler im Log.
Danke :)

**Comment by bolliy** [comment]
Hallo Heiko,
hast du die **DEV-Version** (https://github.com/bolliy/ioBroker.sun2000/tarball/dev) installiert oder die "offizielle latest Version"?
Beide haben die selbe Versionsnummer, da die DEV-Version keine eigene Versionsnummer besitzt, sondern nur ein Abbild der aktuellen Entwicklung ist. 
Geht dein Slave Inverter in Nacht aus? MIt der Dev-Version möchte ich die Timeout-Fehler in dieser Situation beheben.
Stephan

**Comment by luckyheiko** [comment]
hallo, 
habe wohl die 'normale' version, die io broker vorgeschlagen hat.
aber ich habe nur 1 mal die meldungen
<html><body>

sun2000.0 | 2024-02-15 00:49:40.024 | warn | Error while reading from 192.168.10.18 [Reg: 32080, Len: 2, modbusID: 1] with: Timed out
-- | -- | -- | --
sun2000.0 | 2024-02-15 00:49:25.019 | warn | Error while reading from 192.168.10.18 [Reg: 37765, Len: 2, modbusID: 1] with: Timed out
sun2000.0 | 2024-02-15 00:49:10.000 | warn | Error while reading from 192.168.10.18 [Reg: 37765, Len: 2, modbusID: 1] with: Timed out
sun2000.0 | 2024-02-15 00:43:40.002 | warn | Error while reading from 192.168.10.18 [Reg: 37765, Len: 2, modbusID: 1] with: Timed ou


</body>
</html>
und hier denke ich das es die abfrage nicht (offline) WB sind?!

**Comment by bolliy** [comment]
Sofern der WR oder Speicher in STANDBY (Speicher: SLEEP_MODE), dann kommen ein paar Timeouts. Das ist aber auch nachvollziehbar.
Wenn du nichts dagegen spricht, würde ich gern den issue schließen. Ist da ok für dich?
