### ISSUE TITLE
Update Wiki Page / Public installation description help for new users

### ISSUE THREAD

**Issue by TrackerTheCode** [bolliy/ioBroker.sun2000#36]
I would like to update the wiki page or update the readme.md file to provide a quick understanable howto install this nice tool in the io Broker.

Can I support in this case or is someone already working on it?

**Comment by bolliy** [comment]
I'm happy to receive support. You can fork the adapter and send me your changes as a PR. 
An update of the adapter will be released in the next few days.
BR Stephan

**Comment by bolliy** [comment]
WIP

**Comment by bolliy** [comment]
Would you like to submit something - or can I close this issue?
