### ISSUE TITLE
"State of Capacity" value stuck at 5%

### ISSUE THREAD

**Issue by TrackerTheCode** [bolliy/ioBroker.sun2000#37]
**Describe the bug**  
Value is not up2date compared to the SolarFusion Cloud data and other Sun2000-odbus-Adapter:

![grafik](https://github.com/bolliy/ioBroker.sun2000/assets/119059805/150fe5fd-5732-4484-86fe-2271c44ee359)

**Comment by bolliy** [comment]
Please install the new version and test again.
Stephan

**Comment by bolliy** [comment]
A lot of data only becomes available after a while. Only real-time data is read at the interval. otherwise the dongle would be put under too much load.
Please check the log to see if there are any errors. Then put it here.

**Comment by TrackerTheCode** [comment]
Value is updated to a different value, '23%' now. To compairson to the value from Fusion Solar app 16%, still not up2date. 

<img width="1139" alt="grafik" src="https://github.com/bolliy/ioBroker.sun2000/assets/119059805/fd10a878-78fe-4e1f-86e7-96e40cfd0edd">

<img width="1545" alt="grafik" src="https://github.com/bolliy/ioBroker.sun2000/assets/119059805/1e0a3f3d-27ff-42c8-88af-25deef420997">

**Comment by bolliy** [comment]
Ich mach jetzt mal auf deutsch weiter ;)
Fragen:
Wann hast du den Adapter gestartet?
Ist der/die WR in Standby Modus gegangen?
Bitte gleich antworten!
Stephan

**Comment by bolliy** [comment]
Ich kann mir das gerne auf Discord anschauen...

**Comment by TrackerTheCode** [comment]
Jo Können wir machen. auf welchem Server erreiche ich dich?

**Comment by bolliy** [comment]
bolliy_65711

**Comment by TrackerTheCode** [comment]
Reason was the none updated value was my Git-Repo installation. 

Solution: To have everything up2date, I use the NPN-Installation now!
![grafik](https://github.com/bolliy/ioBroker.sun2000/assets/119059805/88f9e627-2e4d-4390-870e-5e19a49a3026)
