### ISSUE TITLE
Fehlernder Datenpunkt: BatteryTemperatur

### ISSUE THREAD

**Issue by MrLee99** [bolliy/ioBroker.sun2000#40]
Moin!

Vielen Dank für den tollen Adapter. Schicke gerade mein Script in Rente.
Dafür würde mir noch die Batterytemperatur fehlen.

Vielen Dank!
Mr.Lee

**Comment by bolliy** [comment]
Danke, das freut mich. 👍 
Die Temp. hängt am Battery Stack. Die bilde ich z.Zt. nicht ab.
Wie viele WR setzt du ein? Hast du mehrere Battery stacks?
Stephan

**Comment by MrLee99** [comment]
Moin,
alles nur kleine Ausstattung 😂 1 wr mit einem battery stack..

**Comment by bolliy** [comment]
Ist bereits in der **DEV-Version** umgesetzt. Wenn du möchtest kannst du die installieren. Siehe:
https://forum.iobroker.net/post/1122230

Den Wert findest du im State sun2000.0.inverter.0.battery.unit.1.batteryTemperature

Ein Release wird noch dauern, da ich gerade der Adapter umstrukturiere.  
Stephan

**Comment by MrLee99** [comment]
Moin! Vielen Dank!

Teste gerade...liefert aber aktuell plausible Werte.

Danke Dir!

**Comment by bolliy** [comment]
ist nun in der V0.3.0 implementiert. Bitte ausprobieren...
siehe: https://forum.iobroker.net/topic/71768/test-adapter-sun2000-v0-1-x-huawei-wechselrichter

Stephan

**Comment by MrLee99** [comment]
Moin!

Passt und liefert plausible Werte.
Allgemein ist die 0.3 top stabil und schnell.

Vielen Dank
Christian

**Comment by luckyheiko** [comment]
Hallo 
gerade aufgefallen, das beim 'schlafen' der speicher bisi heiß ist ;)
![grafik](https://github.com/bolliy/ioBroker.sun2000/assets/26415601/2e80d192-0bef-46af-a280-82efaf9315ee)

**Comment by bolliy** [comment]
Hallo Heike, das ist mir auch schon bei meinem Speicher aufgefallen. Der Wert wird aber tatsächlich über modbus ausgelesen. Ich könnte bei über 100°C den Wert 0 anzeigen. Wäre das ok für dich?

**Comment by bolliy** [comment]
Das ist die größte positive 16 Bit Zahl 32767 / 10. Das sollte ich rausfiltern können.

**Comment by MrLee99** [comment]
Moin!

ist es möglich die Stati "offline" und "Standby" rauszufiltern und dann den Datenpunkt auf einen "dummy-Wert" zu setzen?
Alternativ kann man, wenn die Stati bekannt sind dieses in iob abfangen.

Ich habe festgestellt das alle Stati der Batterie im Standby/offline nicht korrekt sind (schnelle Entladung bis offline im Polling Zeitraum führt ebenfalls zu falscher Anzeige des Batteriestandes).

bis denne
Mr.Lee / Christian

**Comment by bolliy** [comment]
Hallo Christian, grundsätzlich bin ich kein Freund von "geschminkten" bzw. angepassten Werten. So können sich Fehler bei der Interpretation der Werte einschleichen und beim Einsatz z.B. einer neuen Huawei Software Version Nebeneffekte auftreten.
Dann ist auch die Frage nach dem richtigen Dummy-Wert. Dieser könnte dann auch zu einer falschen Interpretation (von der VIS oder Mensch) von Werten führen. Eigentlich wäre der richtige Wert "**Null**". Allerdings kann das wieder in der VIS Probleme machen? Ich würde mich freuen wenn du dieses im Forum zur Diskussion bringen würdest.
https://forum.iobroker.net/topic/71768/test-adapter-sun2000-v0-1-x-huawei-wechselrichter
Vielen Dank!

**Comment by bolliy** [comment]
Neue Test-Version ist raus! Nun kannst du third-party Gerate über den integrierten modbus-proxy einbinden.
Nun sollten die "falschen" Temperaturwerte mit "0" gefüllt werden.

Siehe: https://forum.iobroker.net/post/1132998
