### ISSUE TITLE
Value 'chargeDischargePower' is not refrehsed

### ISSUE THREAD

**Issue by TrackerTheCode** [bolliy/ioBroker.sun2000#47]
**Describe the bug**  
The collected/calculated value 'chargeDischargePower' stays on a old state. It is not refreshed:

![grafik](https://github.com/bolliy/ioBroker.sun2000/assets/119059805/d2aef6b3-0ca3-4e39-9370-a7423ae45be4)

The triggering source value is refreshed frequently: 
![grafik](https://github.com/bolliy/ioBroker.sun2000/assets/119059805/ca06b206-7b72-476b-80b4-4d94f12790c6)

**Versions:**  
 - Adapter version: v0.3.0

**Comment by bolliy** [comment]
Hi Roland,
please, Install from Github
https://github.com/bolliy/ioBroker.sun2000.git
I hope you still have something in your battery ;)
Stephan

**Comment by TrackerTheCode** [comment]
Looks good now ;-)
![grafik](https://github.com/bolliy/ioBroker.sun2000/assets/119059805/3234f562-7b6e-459b-9094-1baf338c9825)

**Comment by bolliy** [comment]
new version v0.3.1 has been released ;)

**Comment by bolliy** [comment]
your comment: https://forum.iobroker.net/post/1128284

Thanks for your support.
Stephan
