### ISSUE TITLE
[Bug]: falsche Einheit

### ISSUE THREAD

**Issue by Peguschwein** [bolliy/ioBroker.sun2000#56]
### The problem

Ich denke das hier nicht die korrekte Einheit hinterlegt ist A anstelle W

### Version of nodejs

Node.js: v18.19.1

### Version of ioBroker js-controller

NPM: 10.2.4

### Version of Adapter

0.4.1

### Repository

ioBroker stable

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [ ] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

![grafik](https://github.com/bolliy/ioBroker.sun2000/assets/160536434/30aa18c6-69ee-414a-ba52-1906f3e8f65a)

**Comment by bolliy** [comment]
bitte v0.5.0 per npm installieren.
Stephan
