### ISSUE TITLE
[Bug]: ständig timeout errors in Version 0.60

### ISSUE THREAD

**Issue by arnovy** [bolliy/ioBroker.sun2000#64]
### The problem

Hi Stephan,

ich habe heute festgestellt, dass der Adapter dauernd in Timeouts läuft, siehe Screenshots.
Ich habe den Haken bei Autoadjust reingemacht und den Adapter neu gestartet, gleiches Fehlerbild. Dann setzt er zwar die Entladeleistung im ioBroker aber nicht in der Batterie (zu sehen im Fusion Portal)

Weiterhin ist mir aufgefallen, dass nach dem neustert des Adapters der Haken bei Autoadjust wieder raus ist. Ist das so gewollt?
Meine Modbus Timings habe ich dir auch mal angehängt. 
![modbus_timings](https://github.com/bolliy/ioBroker.sun2000/assets/17085263/8ecde8b9-1b34-4824-b392-12d804e57102)
![Bildschirmfoto vom 2024-03-27 13-47-34](https://github.com/bolliy/ioBroker.sun2000/assets/17085263/cfc3d084-dd74-48c1-add4-67ab2b831995)

### Version of nodejs

18.16.0

### Version of ioBroker js-controller

5.0.17

### Version of Adapter

0.60

### Repository

ioBroker beta

### Checklist of files to include below

- [ ] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by bolliy** [comment]
Fragt noch ein anderes Gerät (Wallbox, SmartLogger usw.) Daten vom WR?

**Comment by arnovy** [comment]
die Wallbox hängt über den Virtuellen Smartmeter dran, das lässt sich auch nicht anders lösen.
Die Abfragen der Werte funktionieren aber trotzdem ohne Probleme nur wenn ich einen Wert schreibe, in meinem Fall die dischargepower läuft er in Timeout. Wäre es möglich nach dem Schreiben eines Registers 20ms Pause vor den nächsten Abfragen einzufügen? Ich habe mir mal eine Umsetzung in NodeRED angesehen, da wird mit der FlexGatterlösung nach dem Registerschreiben 20ms gewartet

**Comment by bolliy** [comment]
So ich habe das Problem eingegrenzt bzw. reproduzierbar gemacht. 
Im ersten Bild war ich nicht in der Batterie-Konfiguration des FusionSolar Portals. Es treten **keine Timeouts** auf.
Im zweitem Bild bin ich zeitgleich in der Batterie-Konfiguration - nun sehe ich Timeouts!
![grafik](https://github.com/bolliy/ioBroker.sun2000/assets/36469725/f81a7158-051a-4a74-8b32-9dd1db570ce7)

Im FusionSolar Portal werden auch die Werte verspätet oder nicht übernommen. 
Erst ein Refresh + warten + Wechseln der Ansicht akualisiert den Wert von 500 auf 5000

![grafik](https://github.com/bolliy/ioBroker.sun2000/assets/36469725/126b4a2a-ad81-47f1-8dd1-230b82c34980)

Es ist also ein Problem des gleichzeitigen Zufriffs auf den Wechselrichter vom Adapter und des Portals.

Die modbus-Schnittstelle von Huawai ist leider **nicht multi-client-fähig**. Der modbus-Proxy vom Adapter ist aber schon.
Deshalb habe ich auch gleich die Frage nach weiteren Geräten gestellt. Du bist nicht der einzige SCharger Nutzer der Timeout Probleme hat. Und ggf. greift auch der SCharger nicht nur lesend sondern auch schreibend in das Geschehen ein. Was die Sache nicht gerade einfacher macht.
Aber dennoch werde ich ein konfigurierbaren Delay beim Schreiben von Registerwerten einbauen.
Insofern ist das nicht als Bug des Adapters zu bewerten. Vielleicht kann sich Huawei  zu einer besseren modbus Implementierung durchringen. 

Lg Stephan

**Comment by arnovy** [comment]
Danke für die Klarstellung!
Funktioniert wenn man sich nicht ins Portal einloggt ohne Problem trotz Wallbox verbunden mit dem virtuellen Zähler

**Comment by bolliy** [comment]
Super!

Ich glaube da gibt es seitens Huawei noch einige zu verbessern. Die Timeouts sind ein ständiges Ärgernis!
Die Lösung in der NodeRED-Umsetzung hat das Problem nicht beseitigt; durch den langen Delay hatte der SDongle wieder Zeit sich zu berappeln....
Dann brauchen wir eigentlich kein Delay nach dem Schreiben - oder?

**Comment by arnovy** [comment]
ich habs jetzt nochmal nachgetestet, einmal mit anschließendem Login im Portal und einmal ohne. Die Timeouts treten Tatsache nur beim Login im Portal auf. Da wäre ich ja nie drauf gekommen!

Also brauchen wir kein Delay weil somit sinnlos

**Comment by bolliy** [comment]
super, wieder ein Problem gelöst ;)
