### ISSUE TITLE
[Bug]: Adapter wacht nach wenig Sonneneinstrahlung nicht mehr auf

### ISSUE THREAD

**Issue by arnovy** [bolliy/ioBroker.sun2000#72]
### The problem

Hi Stephan,
der Adapter 0.61 ist heute um 8:06 wegen zu wenig Sonneneinstrahlung wieder schlafen gegeangen, allerdings nie mehr aufgewacht.

Nach drei Stunden habe ich ihn dann neu gestartet, danach lief alles wieder.

wäre es möglich den irraditionmode einfach zu deaktivieren? Längen und Breitengrad im Broker sind gesetzt. 

### Version of Adapter

NA

### Repository

ioBroker beta

### Checklist of files to include below

- [ ] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by bolliy** [comment]
Ich habe noch eine Änderung vorgenommen. 
Bitte auf v0.6.2 updaten.
Siehe https://forum.iobroker.net/post/1145740

Stephan

**Comment by bolliy** [comment]
Sofern das Problem gelöst wurde, würde ich diesen issue gerne schließen. 
Ist das in Ordnung?

**Comment by arnovy** [comment]
Hi Stephan,

das Problem trat mit 0.6.2 nicht mehr auf, kann geschlossen werden
