### ISSUE TITLE
Please add 'Backup power SOC' as control parameter

### ISSUE THREAD

**Issue by max19751** [bolliy/ioBroker.sun2000#84]
### What would you like to be added?

Please add 'Backup power SOC' as parameter to read and write

### Why is this needed?

In systems, where a battery and a backup box are installed, the 'Backup power SOC' defines down to what battery minimum level the consumption is limited in case of normal usage. The 'Backup power SOC' is hence the reserve left in the battery in case the system switches to backup power because of a power outage. 
Being able to set this parameter allows the user to define for their own usage scenario how much of the battery is reserve. As this might depend on weather forecast etc, it is a parameter that will be set more frequently when optimising the battery usage.

**Comment by bolliy** [comment]
Hi Max,
Do you mean the register address 47102?
![grafik](https://github.com/bolliy/ioBroker.sun2000/assets/36469725/977479c1-4b8a-4c4d-86cc-292b1151443b)

**Comment by max19751** [comment]
Hi, yes, indeed, this is what I mean.

**Comment by bolliy** [comment]
Hi Max, dein issue ist umgesetzt. 
LG Stephan

**Comment by max19751** [comment]
Hi Stephan, vielen Dank! Gestestet, funktioniert.
LG Max
