### ISSUE TITLE
Batterypack-Daten ergänzen 

### ISSUE THREAD

**Issue by besimo1** [bolliy/ioBroker.sun2000#85]
### What would you like to be added?

**Bitte folgende Batterie-Register ergänzen (evtl. als Option auswählbar in den Instanzeinstellungen):**
**37814** [Energystorage unit1] **Softwareversion**
37920, 37921, 37922, 37921 [Energystorage unit1][Batterypack 1,2 und 3] SOH Calibration Status
**38210, 38252, 38294, 38336, 38378, 38420** [Energystorage unit1,2][Batterypack 1,2 und 3] **Firmwareversion**
38228, 38270, 38312, 38354, 38396, 38438 [Energystorage unit1,2][Batterypack 1, 2 und 3] Workingstatus
**38229, 38271, 38313, 38355, 38397, 38439**  [Energystorage unit1,2][Batterypack1, 2 und 3] **SOC**
**38223, 38275, 38317, 38359, 38401, 38443**   [Energystorage unit1,2][Batterypack 1, 2 und 3] **Charge/Dischargepower**
**38235, 38277, 38319, 38361, 38403, 38445**  [Energystorage unit1,2][Batterypack 1, 2 und 3] **Voltage**
38236, 38278, 38320, 38362, 38404, 38446   [Energystorage unit1,2][Batterypack 1, 2 und 3] Current
**38238, 38280, 38322, 38364, 38406, 38448**  [Energystorage unit1,2][Batterypack 1, 2 und 3] **Totalcharge**
**38240, 38282, 38324, 38366, 38408, 38450**  [Energystorage unit1,2][Batterypack 1, 2 und 3] **Totaldischarge**
38452, 38454, 38456, 38458, 38460, 38462  [Energystorage unit1,2][Batterypack 1, 2 und 3] Maximum temperature
38453, 38455, 38457, 38459, 38461, 38463  [Energystorage unit1,2][Batterypack 1, 2 und 3] Minimum temperature

(Hinweis Bei Unit2 ProductMode steht in der Erklärung reg. 37089, in den Modbus Interface
Definitions vom 16.02.2023 steht "47089" )

### Why is this needed?

**### Allg. Batterieüberwachung**
z.B. zur Erkennung, ob ein Garantiefall vorliegt (z.B. Kapazitätsverlust eines einzelne Batteriepacks - berechnet aus tatsächlicher Lade-/Entladekapazität des einzelnen Batteriepacks, da SOC stark schwankt).
Überwachung der Akkuspannung der einzelnen Batteriepacks - Profis erkennen an den Spannungen viel genauer, als am SOC, ob ein Problem vorliegt.
Überwachung der Firmewareversionen (mir wurde bereits zweimal ungefragt einmal eine neue und einmal eine ältere Firmware aufgespielt)=>historische_Daten der installierten Firmwarestände (Datum der Updates) möglich
Berechnung des Batteriewirkungsgrades (hier gab es zusätzlich zu dem ohnehin schon schlechten Batteriewirkungsgrades der Luna mit dem Update auf Firmware v127 bei mir nochmal zusätzlich einen extremen Effizienzverlust gegenüber v119 und v125)
Überwachung der Temperatur (z.B. Begrenzung Lade- / Entladeleistung, wenn Temperatur eines Batteriepacks einen Schwellwert überschreitet zur Schonung der Batterie).
Mein Ziel ist es, FusionSolar irgendwann nicht mehr zu benötigen. Dazu fehlen mir noch die Daten der einzelnen Akkus.

**Comment by bolliy** [comment]
@besimo1 ich kann sicherlich einige Batteriedaten zusätzlich aufnehmen. Nur sehe ich die Stabilität des Adapters bei der großen Anzahl von zusätzlichen Daten gefährdet. Wenn wir zu viele Daten in einem Zeitraum gelesen werden, dann wird der sDongle instabil. Gerade die Überwachung der Batteriepacks sehe ich kritisch. Zumal ich dann auch eine weitere Abfrageschleife bräuchte.
Ich möchte dir gerne bei deinem Garantiefall helfen. Könntest du die Anzahl der Register auf ein Minimum reduzieren?

**Comment by besimo1** [comment]
Danke schon Mal im Voraus für die Hilfe.
Ich selbst habe den Luna-10-S1 mit zwei Batterypacks. Erläuft bei mir unter Unit 2. Deshalb brauche ich die Werte für Unit2 und Batterypack 1 und 2
Für die Überprüfung der Garantie wären am Wichtigsten in absteigender Reihenfolge:
- **38366, 38408 [Energystorage unit2][Batterypack 1, 2 ] Totaldischarge**
- **38364, 38406 [Energystorage unit2][Batterypack 1, 2 ] Totalcharge**
- **38361, 38403 [Energystorage unit2][Batterypack 1, 2 ] Voltage**
- 38355, 38397 [Energystorage unit2][Batterypack1, 2] SOC
- 38359, 38401 [Energystorage unit2][Batterypack 1, 2] Charge/Dischargepower
VG
Besimo

**Comment by bolliy** [comment]
Hallo @besimo1 ich könnte dir eine eingebe Version basteln, die für dich die o.g. Register abfragt und als State speichert.
Würdest du im Gegenzug deine Auswertungen, Erfahrungen und den Verlauf deines Garantiefalls im Forum posten?
Ich glaube so könnten auch andere von deinen Erfahrungen profitieren.
Wie ist deine Haltung dazu?

Stephan

**Comment by besimo1** [comment]
Hallo Stephan,
ich will nicht zu viel versprechen und weiß noch nicht, wieviele Details ich öffentlich von dem Garantiefall im Einzelnen posten will.
Ich habe so ein paar Ideen zur Programmierung, z.B. will ich mir ein Script erstellen, mit dem ich per Button die Restkapazität jedes einzelnen Speichermoduls durch erzwungenes Laden mit vorgegebener Lade-/Entladeleistung gemäß den Garantiebestimmungen bestimme (laut Huawei-Support (Stand vor einigen Monaten) gibt es in FusionSolar kein Programm für die Bestimmung der Restkapazität).
Wenn ich tatsächlich so ein Script erstellt habe, könnte ich es im Forum veröffentlichen und ein paar Worte / Erklärungen dazu schreiben und z.B. die Auswertung eines Kapazitätstests posten.
VG
Besimo

**Comment by besimo1** [comment]
...
und es wäre schon gut, wenn alle 5 (bzw. 10) Werte / Register abgefragt werden würden, also auch SOC und die Lade-/Entladeleistung jedes Batterypacks, so dass man auch nachweisen kann, dass die Vorgaben der Garantiebedingungen auch beim Test für jeden einzelnen Akkupack eingehalten wurden.

**Comment by bolliy** [comment]
ok, dann werde ich das in den nächsten Tagen angehen...

**Comment by bolliy** [comment]
Hallo Besimo,
ich habe nun eine Version für dich gebaut.
Die Installation erfolgt über den Expertenmodus. Danach auf die „Krakenkatze“ klicken und dann die benutzerdefinierte Url
https://github.com/bolliy/ioBroker.sun2000/tarball/besimo1
eingeben und die Installation starten. Bitte nach der Installation den Adapter manuell neu starten!

Stephan

**Comment by besimo1** [comment]
Vielen Dank Stefan für die exklusive Version für mich,

läuft bisher super und stabil, außer TotalDischarge wird nur 0 angezeigt:
![image](https://github.com/bolliy/ioBroker.sun2000/assets/101955988/fc09e088-3b03-47bb-9adf-65df8dd6b131)
(chargeDischargePower ist gerade null, da Akkkus voll sind)

Die Nummer 38666 und 38408 müssten aber passen laut Liste Modbus Interface Definition (Issue 5 vom 16.02.2023).

Ich habe mir ein Script geschrieben und mit Hilfe der Werte für chargeDischargePower für Akku1 und 2 die Werte im Minutentakt addiert. Da gibt es Abweichungen zu TotalCharge und Lade- und Entladekapazitaet des Speichers (currentDayChargCapacity und currentDayDischargeCapacity) und Fusion Solar.
Ich vermute, dass bei Batterie-Firmware v127 und v621 ein Fehler bei der Ermittlung der Entladeleistung vorliegt. Muss ich aber noch genauer beobachten.

zur Info meine Instanzeinstellungen:
![image](https://github.com/bolliy/ioBroker.sun2000/assets/101955988/63e157c5-4f6e-45f7-9a5e-e60758291a95) 
![image](https://github.com/bolliy/ioBroker.sun2000/assets/101955988/0a11997e-55ac-4a0b-adbf-078f8b54f13c)
![image](https://github.com/bolliy/ioBroker.sun2000/assets/101955988/21fb7e03-fae5-494b-beed-9d2e696d55ae)
![image](https://github.com/bolliy/ioBroker.sun2000/assets/101955988/eeca8dcf-f708-44e6-b777-b965510bcf56)

VG
Besimo

**Comment by bolliy** [comment]
Hi @besimo1, ich glaube den Fehler bei mir gefunden zu haben. (date reg length was too short)
Installiere mal erneut und den Neustart nicht vergessen!

LG Stephan

**Comment by besimo1** [comment]
Funktioniert !

**Comment by bolliy** [comment]
Kann ich dein issue schießen?

**Comment by besimo1** [comment]
Sorry für die späte Antwort (ich habe ein Zeit-Problem).

Sind dann die BatteryPack-Adressen auch in den zukünftigen Versionen enthalten - z.B. in v0.11 ?

Falls nicht, darf ich dann nicht mehr updaten (ich will diese Daten auch in Zukunft in meiner Visualisierung haben) ?

Mit den BatteryPack-Daten kann man die Batterieeffizienz bestimmen. Das ist wichtig, da es offensichtlich zwischen Versionen v119/v125 und v127/v621 deutliche Unterschiede gibt. Ich werde in den nächsten Tagen die Firmware wieder downgraden auf v125, da v621 an manchen Tagen deutlich ineffizienter ist, als v119/v125.

Hier ein Auszug aus meiner View:
![image](https://github.com/bolliy/ioBroker.sun2000/assets/101955988/3458f9f1-aaca-4d66-8eff-62e0f118865e)
![image](https://github.com/bolliy/ioBroker.sun2000/assets/101955988/773bc898-d363-43b6-ac95-99da11b36841)

**Comment by bolliy** [comment]
Zur Zeit sind die Änderungen in der v0.11.0 zu v0.10.0 minimal. Also für dich nicht von Relevanz.
Ich kann aber in der nächsten minor release einen versteckten Schalter einbauen. Dann kannst du deine BatteryPack Daten einschalten. 
Sofern es soweit ist, werde ich dich hier informieren.
Dein issue bleibt bis dahin weiter offen....

**Comment by besimo1** [comment]
Danke, dass du extra für mich einen versteckten Schalter einbauen willst.

Grundsätzlich würde ich es natürlich begrüßen, wenn der Schalter für alle zugänglich wäre und alle Akkukonfigurationen (unit 1 + 2, Akku 1 bis 3) möglich wären.

Ich weiß nicht, inwieweit sich andere User für dieses Feature interessieren. Vielleicht schreiben hier andere User, ob sie an diesem Feature interessiert sind, solange das issue offen ist.

Für mich allein reicht natürlich der versteckte Schalter.

**Comment by fuStefan** [comment]
Hi, für mich sind die zusätzlichen Daten auch sehr interessant, einfach nur um sie zu loggen und die Entwicklung über die Jahre zu beobachten. Vielleicht könntest du einen offiziellen Schalter in der Adapterkonfiguration vorsehen.

**Comment by bolliy** [comment]
In der v0.12 sind nun die Battery Packs enthalten.

https://forum.iobroker.net/topic/71768/test-adapter-sun2000-v0-1-x-huawei-wechselrichter/547?_=1727103674960

LG Stephan

**Comment by bolliy** [comment]
@besimo1 ich würde gerne das issue schließen. Ist das ok für dich?
