### ISSUE TITLE
Support for new Battery System Luna2000-21-S1

### ISSUE THREAD

**Issue by fritzrichter** [bolliy/ioBroker.sun2000#86]
### What would you like to be added?

I installed the new Luna-S1 Battery System, which is not identified right now, I guess new registers are used. We could work together if you reach out and change the plugin so that the metrics are imported correctly.

### Why is this needed?

Would like to see all KPIs as well in the system.

**Comment by bolliy** [comment]
Do you have the modbus definitions for your new storage? Otherwise I can't implement your issue.

**Comment by bolliy** [comment]
Is the **battery** path behind the inverter empty or has data been written there?

**Comment by bolliy** [comment]
If you don't mind, we can continue in German...

**Comment by fritzrichter** [comment]
Alles klar ;) ich sammle mal mehr Infos und versuche die Register manuell zu lesen und gebe Bescheid… Danke für die schnelle Antwort ;)

**Comment by fritzrichter** [comment]
Ich habe den Fehler auf meiner Seite gefunden! Nach einer Anpassung verhält sich der Luna S1 nun so wie der alte und die Werte werden korrekt importiert. Großartig :) Schließe das Ticket daher.
